include:
- ./fortunewhale/fortune.sh
kind: ArchiveUploadSpec
name: fortunewhale-fortune-sh-m6GY

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fortune-204208ba-e83a-4817-9a0e-c6a0a586c12b
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fortunewhale-fortune-sh-m6GY
  environment:
    name: binary
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2020-05-29T20:00:36Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fortune
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: binary
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: fortune-204208ba-e83a-4817-9a0e-c6a0a586c12b
      namespace: default
  resources: {}
  secrets: null
