apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: fortunewhale
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fortunewhale
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /fortunewhale
    tls: ""
  method: GET
  relativeurl: /fortunewhale
